### SIGN UP
POST http://localhost:3000/api/v1/auth/signup 
Content-Type: application/json
{
    "email": "ptan21@clc.fitus.edu.vn",
    "fullname": "Phan Thanh An",
    "password": "ptan21@1234",
    "phone": "0325364475",
}

### SIGN IN
POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json
{
    "email": "ptan21@clc.fitus.edu.vn",
    "password": "ptan21@1234",
}

### FORGOT PASSWORD
POST http://localhost:3000/api/v1/auth/signin
Content-Type: application/json
{
    "email": "ptan21@clc.fitus.edu.vn"
}