### SHOW ALL CATEGORY
GET http://localhost:3000/api/v1/category/list
Content-Type: application/json

### CREATE CATEGORY
POST http://localhost:3000/api/v1/category/create
Content-Type: application/json
{
    "name": "Information Technology",
    "image": {
        "url": "https://news.workforce.com/wp-content/uploads/sites/2/2018/12/AI-is-coming-%E2%80%94-and-HR-is-not-prepared.jpg",
        "width": 750,
        "height": 500 
    }
}

### DELETE CATEGORY
DELETE  http://localhost:3000/api/v1/category/delete
Content-Type: application/json
{
    "category_id": 1
}