### REQUEST UPGRADE TO RETAILER
POST http://localhost:3000/api/v1/user/upgrade 
Content-Type: application/json
{
    "user_id": 1
}

### ACCEPT UPGRADE TO RETAILER -- SEND 2 API
UPDATE http://localhost:3000/api/v1/user/update
Content-Type: application/json
{
    "user_id": 1,
    "role": "retailer"
}

UPDATE http://localhost:3000/api/v1/request/update
Content-Type: application/json
{
    "request_id": 1,
    "request_status": "accepted"
}

### DENY UPGRADE TO RETAILER
UPDATE http://localhost:3000/api/v1/request/update
Content-Type: application/json
{
    "request_id": 1,
    "request_status": "denied"
}
